blank_issues_enabled: false
contact_links:
-   name: Ask the community for help
    url: https://github.com/microsoft/dbt-fabricspark/discussions
    about: Need help troubleshooting? Check out our guide on how to ask
-   name: Contact dbt Cloud support
    url: mailto:support@getdbt.com
    about: Are you using dbt Cloud? Contact our support team for help!
-   name: Participate in Discussions
    url: https://github.com/dbt-labs/dbt-adapters/discussions
    about: Do you have a Big Idea for dbt-adapters or one of the adapter implementations? Read open discussions, or start a new one
-   name: Create an issue for dbt-fabricspark
    url: https://github.com/microsoft/dbt-fabricspark/issues/new/choose
    about: Report a bug or request a feature for dbt-core