name: "privy_demo"
version: "1.0.0"
config-version: 2

profile: "privy_demo"

model-paths: ["models"]

target-path: "target"
clean-targets:
  - "target"
  - "logs"

models:
  privy_demo:
    materialized: view
